# docker compose  -p instantmesh up --remove-orphans

services:
  blender4.2 :    
    image: registry.light-field.tech/citygen/blender:4.2   
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN                                           
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0'] # ['1', '3'] 
            capabilities: [gpu]           
    environment:            
      - DISPLAY
    init: true
    ipc: "host"
    network_mode: host
    # ports:
    #   - "8099:8099"
    runtime: nvidia      
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864            
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw    
      - /etc/localtime:/etc/localtime:ro      
      - ./:/workspace
      - /city_gen:/city_gen          
    working_dir: /workspace
    command: [ "tail", "-f"]