# docker build --progress plain --network=host -f Dockerfile.4.2 -t registry.light-field.tech/citygen/blender:4.2 .
# --build-arg http_proxy=http://127.0.0.1:11000 --build-arg https_proxy=http://127.0.0.1:11000


FROM nvcr.io/nvidia/cuda:12.1.1-devel-ubuntu22.04

ENV NVIDIA_DRIVER_CAPABILITIES all

ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ 

RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy main restricted universe multiverse" > /etc/apt/sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy-backports main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse" >> /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    apt-get update && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get purge -y --auto-remove python3 && \
    apt-get install -y python3.10 python3.10-dev python3.10-distutils wget && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1

RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    pip install --upgrade pip pysocks

# blender
WORKDIR /app

RUN wget https://download.blender.org/release/Blender4.2/blender-4.2.0-linux-x64.tar.xz && \
    tar -xvf blender-4.2.0-linux-x64.tar.xz && rm blender-4.2.0-linux-x64.tar.xz

ENV PATH="/app/blender-4.2.0-linux-x64:${PATH}"      

RUN apt-get update && \
    apt-get install -y libx11-6 libxrender1 libxxf86vm1 libxfixes3 libxi6 libxkbcommon0 libsm6 libgl1-mesa-glx libfreeimage3 libfreeimage-dev

RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple 'tqdm' 'typer'

RUN apt-get update && \
    apt-get install -y unzip htop